// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikswsvmfohxmnmmhzmry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlrc3dzdm1mb2h4bW5tbWh6bXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzI3ODIsImV4cCI6MjA2NjAwODc4Mn0.HCmbZP79CWpKjRVKNtrfwQmnk7Rt-9XXYxi-rXqPIC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);